Update compile to detect OSGi

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,18 +1,18 @@
 #!/bin/sh
+# bin/compile <build_dir> <cache_dir>
 
-indent() {
-  sed -u 's/^/       /'
-}
+#fail fast
+set -e
 
-echo "-----> Found a hello.txt"
+echo "-----> Compiling OSGi app."
 
-# if hello.txt has contents, display them (indented to align)
-# otherwise error
+# parse arguments
+BUILD_DIR=$1
+CACHE_DIR=$2
 
-if [ ! -s $1/hello.txt ]; then
-  echo "hello.txt was empty"
-  exit 1
-else
-  echo "hello.txt is not empty, here are the contents" | indent
-  cat $1/hello.txt
-fi | indent
+echo "------> Build dir - $BUILD_DIR"
+echo "------> Cache dir - $CACHE_DIR"
+
+# start OSGi
+
+exit 0
